### PR TITLE
Multiple relations on single parameter

### PR DESCRIPTION
**Pull request by andrew-boyarshin**
Example: [IUIAnimationInterpolator2::SetInitialValueAndVelocity](https://docs.microsoft.com/en-us/windows/win32/api/uianimation/nf-uianimation-iuianimationinterpolator2-setinitialvalueandvelocity), `cDimension` there is a length for both `initialValue` and `initialVelocity`), e.g. `length(initialValue),length(initialVelocity)`.

* Use `IList<MarshallableRelation>` to store all relations on a parameter
* Reimplement `RelationParser` to be a proper language parser using Roslyn
* Drop `IHasRelatedMarshallable` interface
* Prevent crash when relation specifies parameter name, which is absent on the method. Print helpful message instead.
* Drop workaround for [SDK issue](https://github.com/dotnet/sdk/issues/11407), since the fix made its way to daily build. Affected `Microsoft.NET.Sdk` versions - only 5.0 previews up to `5.0.100-preview.5.20230.9` (first version to contain the fix).
* Add advanced test log message assertion facilities
* Fix `MarshalledElementFactoryTests.ParameterWithStructSizeRelationLogsError` testing the wrong thing

### CODE REVIEW

**Comment by andrew-boyarshin** [comment]
After sending this PR, I've started writing tests. While everything I've tested on works correctly, I'm worried about `const` relation. Before this PR, when there was only one relation, it was simple: everything between the first and last bracket is value to be stored for later use. Now, I've implemented custom language (there is even support for string literals, not pushed to remote for now), and it still doesn't guarantee that some complex const expression wouldn't confuse the parser. I have an idea how to solve the problem: reuse Roslyn. Wrap passed string in `new[] { ... }`, call `ParseExpression` and traverse C# syntax tree that is guaranteed to be completely correct.

**Comment by andrew-boyarshin** [comment]
@jkoritzinsky ready to be reviewed.

**Comment by andrew-boyarshin** [comment]
Note, that this PR enables new syntax: `Length`, `Const` and `StructSize` instead of the older variants. Older variants are still supported via string replacement, but that's obviously non-ideal. If `const` or `struct-size` occur in substring of relation arguments, they will be replaced too, but warning will be emitted (the least I can do).
The new syntax should be documented, but I would like to postpone the changes to the docs till later PRs (I expect more to come, the next one will be about value type marshalling and/or MSBuild SDK targets file refactoring).

After some work on SharpGen, is the targets split (made in #20) necessary anymore? There is no more CodeGenApp. I think about batching these targets and tasks. That will remove mandatory loading & writing of large XML files on every build. This is also a blocker for moving from CastXML, potential Source Generators and Function Pointers proposal adoption.

**Comment by jkoritzinsky** [comment]
Some of the tasks (the ones that discover which C++ files are inputs and which C# files are outputs) definitely need to stay separate. The rest of them could probably merge together. My goal with the separation was to enable generation to work incrementally,  but the design of the config files breaks that.

**Comment by andrew-boyarshin** [comment]
@jkoritzinsky yep, I agree the tasks that compute inputs/outputs must stay separate.

> My goal with the separation was to enable generation to work incrementally, but the design of the config files breaks that.

Could you please elaborate on that? I mean, I think it's because the config files specify inputs (source headers) MSBuild is not aware of, but I haven't given it much thought. What do you think is the cause of SharpGen regenerating everything almost on every build?

Meanwhile (waiting on this PR to be reviewed and merged), I'm having a look at #144. The patch there is insufficient (even SdkTests are failing, and for a good reason), I'm working on a better solution.

**Comment by jkoritzinsky** [comment]
There are a few MSBuild tasks that the targets files use to enable discovering all of the input headers into SharpGenTools so that we re-run generation when only the native headers are changed and not require extraneous edits to the mapping files.

**Comment by andrew-boyarshin** [comment]
@jkoritzinsky it still doesn't explain why SharpGen 1.2 sometimes regenerates bindings for no good reason (observed numerous times, but I couldn't grab binlog since I was using Rider IDE). Meanwhile, I'm finishing my rework of SharpGen targets for v2:
1. Single task for running SharpGen, greatly simplified targets file
2. All outputs are now static (that is, 5 generated `.cs` files contain code for all namespaces/config files, no subfolders for generated files)
3. Well-defined up-to-date checks behavior (with extensive documentation based on actual MSBuild sources)
4. Fixed missed regeneration when using undocumented `<file />` config file inclusion method
5. Reimplemented documentation providers extensibility point from scratch to use Roslyn approach (like the one used for Analyzers/Source Generators, but based on implementing the interface instead of being marked with an attribute)
6. Reimplemented MSDN doc provider (MSDN retired, Microsoft Docs are used now), added tests

This will take a couple more days, then I'll push it to draft PR branch. I hope _this_ PR will be reviewed & merged by that time.

**Comment by jkoritzinsky** [comment]
Rider’s usage of MSBuild is particularly poor since they try to do shortcuts. I wouldn’t be amazed if they broke things.

I’ll try to review this over the weekend so we can get it merged in.

**Comment by andrew-boyarshin** [comment]
<just a friendly reminder and an update on the following PRs>
1. Now there are only 3 tasks (SharpPatch, SharpGen and a new SharpGen-related task for a new property cache), solid target up-to-date checks behavior
2. All unit tests are now in a single project (fixes dotCover not showing the results properly in Rider and reduces test logger code duplication)
3. Extensions don't work now (extension assembly dependencies fail to load). This so obviously should work that I don't know why it doesn't, I feel like it's either a bug in `AssemblyLoadContext`, or myself, probably the latter. I'll fix that, of course, but today was a disappointing day.
4. `SharpGenTools.Sdk` is now an actual MSBuild SDK, removes the need to remember to specify PrivateAssets attribute on a PackageReference
5. `SharpGen.Runtime` is now implicitly referenced (always correct matching version)
6. Filed/hit some NuGet and MSBuild issues. Nothing critical, but one issue was somewhat annoying.

**Comment by jkoritzinsky** [comment]
That work sounds fantastic! I’ve merged this PR in in the meantime so we can keep moving forward.

**Pull request merged**
