### PR TITLE
My patchset without SDK targets, docs & extensibility rework

### PR DESCRIPTION
**Pull request by andrew-boyarshin**
* Add net5.0 to SharpGen.Runtime to actually provide extended NativeLong/NativeULong API surface
* Generate callback interface members even if autogen-shadow is set to false (with proper visibility modifier), supercedes #144, which is an incorrect implementation of the feature
* Add generation of raw data block copy code for ref/out value type array parameters
* Simplify nested ifs by introducing additional properties (like CsCallable.HasReturnTypeValue)
* Extend InteropType to support unsigned primitive types
* Enhanced DocUnmanagedName for properties
* SharpGenTools now almost functional as MSBuild SDK (as opposed to old PackageReference method)
* Fix mapping functions returning HRESULT to functions returning int (generate a cast expression to use an explicit conversion operator)
* Fix more cases where parameter is used as return value
* Fix ref/out value type arrays (were wrongly forced to be In)
* Dropped support for legacy documentation providers (removed DocItem.cs)
* Various clean-ups

### CODE REVIEW

**Comment by andrew-boyarshin** [comment]
I'll clean up this PR tomorrow (remove most whitespace-only/swapping-declaration-order changes) and fix build (feels like CI VSTest problem). But I consider this ready for review, since it is feature-complete. With this, diff to my local 2.0 branch reduces substantially.

Removed docs extensibility will return (greatly rewritten) in the Episode 6 PR, since Episode 5 will be about merging MSBuild tasks and reworking cache invalidation.

@jkoritzinsky

**Comment by amerkoleci** [comment]
@jkoritzinsky any plans to update this project? Tell me because my Vortice.Windows depends on SharpGen, otherwise I gonna keep personal fork

**Comment by andrew-boyarshin** [comment]
@amerkoleci btw, you might be interested in my mostly complete Microsoft Docs doc provider that will enable you to fix amerkoleci/Vortice.Windows#69 automagically. I am working right now on C# 9.0 function pointers native invocation impl, but I will push everything as soon as I consider it to be mostly working. #161 is my primary dev branch.

**Review by jkoritzinsky — APPROVED** [review]
LGTM. Since you've been doing so many great contributions for SharpGenTools recently, I'm going to add you as a member of the org. Thanks!

**Comment by amerkoleci** [comment]
Any chance we get update on nuget? At least for the runtime part?

**Comment by andrew-boyarshin** [comment]
I'm working on preparing Episode 5 PR right now. I also have no objections to creating first 2.0 beta release, since it will allow for early 2.0 feedback. If @jkoritzinsky concurs this is the right thing to do, creating a tag should automatically publish a NuGet release.

**Comment by jkoritzinsky** [comment]
I might need to update our NuGet API key for publishing a new package, but other than that we can create a 2.0 beta 1 release.

**Comment by amerkoleci** [comment]
I think having beta release doesn't hurt and can help others to test it

**Pull request merged**
